# Your full site URL. Example:
# "https://<username>.neocities.org/"
baseURL = "https://thegreekgeek.neocities.org/"
languageCode = "en-us"
# Title of your site
title = "TESTING TESTING"
# How many feed entries to load at once
paginate = 6
theme = 'neofeed-theme'
[taxonomies]
tag = "tags"
slashes = "categories"

[author]
name = "thegreekgeek" # Your online name
# Your profile image. External link or relative to static/. Examples:
# "https://imgur.com/123456788"
# "image/me.webp"
image = "https://cdn.some.pics/thegreekgeek/677c6f3894200.png"
about = "I like to tinker with things."

[params]
# Name of a file in static/skins/ without the ".css" extension
skin = "minimal"

#
# Totally optional cool stuff (see README for details)
#
# socialImage = "static/img/social.png" # site image for rich embeds
# customCSS = "css/style.css" # relative to ./static/
# plausible = true
# paymentPointer = "$wallet.provider.com/myspecialid123"
webmentionUrl = "https://webmention.io/thegreekgeek.neocities.org/webmention"
pingbackUrl = "https://webmention.io/thegreekgeek.neocities.org/xmlrpc"
micropubUrl = "https://equatorial-tough-yamamomo.glitch.me/micropub/main"
microsubUrl = "https://aperture.p3k.io/microsub/958"

#
# For IndieAuth and the author card
#
githubuser = "thegreekgeek"
# twitteruser = "chihiro" # no @ in front
mastodon = "https://mstdn.io/@thegreekgeek" # full link to your instance profile

[permalinks]
# Format for feed entry links. You probably don't need to change this.
feed = "/:title/"
categories = "/:section/:title"

[outputs]
# Output formats for your feed. You probably don't need to change this.
  home = ["HTML", "JSON", "RSS"]